language: go

go:
  - "1.12"
  - "tip"

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -coverprofile=coverage.txt -covermode=atomic
  - go test -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
